---
kind: pipeline
name: build_amd64

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    build_args:
    - BASE=python:alpine
    - arch=amd64
    cache_from:
    - angelnu/i2c-relay:master-amd64
    - "angelnu/i2c-relay:${DRONE_BRANCH}-amd64"
    - "angelnu/i2c-relay:${DRONE_BRANCH}-amd64"
    - python:alpine
    password:
      from_secret: DOCKER_PASS
    repo: angelnu/i2c-relay
    tags:
    - "${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT}-amd64"
    - "${DRONE_BRANCH}-amd64"
    - latest-amd64
    username:
      from_secret: DOCKER_USER

---
kind: pipeline
name: build_arm

platform:
  os: linux
  arch: arm

steps:
- name: docker
  image: plugins/docker
  settings:
    build_args:
    - BASE=python:alpine
    - arch=arm
    cache_from:
    - angelnu/i2c-relay:master-arm
    - "angelnu/i2c-relay:${DRONE_BRANCH}-arm"
    - "angelnu/i2c-relay:${DRONE_BRANCH}-arm"
    - python:alpine
    password:
      from_secret: DOCKER_PASS
    repo: angelnu/i2c-relay
    tags:
    - "${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT}-arm"
    - "${DRONE_BRANCH}-arm"
    - latest-arm
    username:
      from_secret: DOCKER_USER

---
kind: pipeline
name: build_arm64

platform:
  os: linux
  arch: arm64

steps:
- name: docker
  image: plugins/docker
  settings:
    build_args:
    - BASE=python:alpine
    - arch=arm64
    cache_from:
    - angelnu/i2c-relay:master-arm64
    - "angelnu/i2c-relay:${DRONE_BRANCH}-arm64"
    - "angelnu/i2c-relay:${DRONE_BRANCH}-arm64"
    - python:alpine
    password:
      from_secret: DOCKER_PASS
    repo: angelnu/i2c-relay
    tags:
    - "${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT}-arm64"
    - "${DRONE_BRANCH}-arm64"
    - latest-arm64
    username:
      from_secret: DOCKER_USER

---
kind: pipeline
name: build_manifest

platform:
  os: linux
  arch: amd64

steps:
- name: "manifest_${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT}"
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: DOCKER_PASS
    platforms:
    - linux/amd64
    - linux/arm
    - linux/arm64
    target: "angelnu/i2c-relay:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT}"
    template: "angelnu/i2c-relay:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT}-ARCH"
    username:
      from_secret: DOCKER_USER

- name: "manifest_${DRONE_BRANCH}"
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: DOCKER_PASS
    platforms:
    - linux/amd64
    - linux/arm
    - linux/arm64
    target: "angelnu/i2c-relay:${DRONE_BRANCH}"
    template: "angelnu/i2c-relay:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT}-ARCH"
    username:
      from_secret: DOCKER_USER

- name: manifest_latest
  image: plugins/manifest:1
  settings:
    ignore_missing: true
    password:
      from_secret: DOCKER_PASS
    platforms:
    - linux/amd64
    - linux/arm
    - linux/arm64
    target: angelnu/i2c-relay:latest
    template: "angelnu/i2c-relay:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT}-ARCH"
    username:
      from_secret: DOCKER_USER

depends_on:
- linux/amd64
- linux/arm
- linux/arm64

...
